apiVersion: apps/v1
kind: Deployment
metadata:
  name: microcinemafood-deploy
spec:
  selector:
    matchLabels:
      app: hello-backend
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-backend
    spec:
      containers:
      - name: back-pod
        image: trabajogestion/cinemafood
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: 128Mi
            cpu: 0.1