apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: hello-world
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: microfront
        image: trabajogestion/cinema-app
        ports:
        - containerPort: 4200
        resources:
          limits:
            memory: 128Mi
            cpu: 0.1
