apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-cinema-eats
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-world
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: cinema-eats-pod
        image: trabajogestion/cinemaseats
        ports:
        - containerPort: 82
        resources:
          limits:
            memory: 128Mi
            cpu: 0.1
