apiVersion: v1
kind: Pod
metadata:
  name: frontendpod
  labels:
    zone: prod
    version: v1
spec:
  containers:
  - name: hello-ctr
    image: trabajogestion/cinema-app
    ports:
    - containerPort: 4200
    resources:
      limits:
        memory: 256Mi
        cpu: 0.5
