apiVersion: v1
kind: Pod
metadata:
  name: cinema-eats-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
  - name: hello-ctr
    image: trabajogestion/cinemaseats
    ports:
    - containerPort: 82
    resources:
      limits:
        memory: 256Mi
        cpu: 0.5